Statistics panel for selected car
marc7s/TrafficSimulator pull request #102
Opened 2023-03-31 19:32 UTC by Marre-B

Working statistics window with 3 tabs as of yet. Only 1 field (total distance) in info is currently displaying an actual value from the selected car.

2023-03-31 19:42 UTC, hannes44 commented on TrafficSimulator/Assets/UI/Statistics/Info/InfoController.cs
> +        //_totalTimeOnRoad.text = car.
Remove comment

2023-03-31 19:42 UTC, hannes44 commented on TrafficSimulator/Assets/UI/Statistics/Info/InfoController.cs
> +        _totalDistanceTraveled.text = car.TotalDistance.ToString("0.00");
Should add m after or could do km

2023-03-31 19:42 UTC, hannes44 commented on TrafficSimulator/Assets/UI/Statistics/Settings/SettingsController.cs
> +       // _totalDistanceTraveled = _doc.rootVisualElement.Q<Label>("TotalDistanceTraveled");
Remove the comments

2023-03-31 19:42 UTC, hannes44 commented on TrafficSimulator/Assets/UI/Statistics/StatisticsController.cs
> +            Debug.Log("Stats");
Since the button action is implemented you should remove the log

2023-03-31 19:42 UTC, hannes44 commented on TrafficSimulator/Assets/UI/Statistics/Stats/StatsController.cs
> +        //_totalTimeOnRoad = _doc.rootVisualElement.Q<Label>("TotalTimeOnRoad");
Remove the comments

2023-03-31 20:02 UTC, marc7s requested changes

2023-03-31 20:02 UTC, marc7s commented on TrafficSimulator/Assets/User/CarSelectable.cs
> +using Car;
Same here, why was this added when nothing else was changed?

2023-03-31 20:29 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/Stats/StatsController.cs
> +    }
Empty function?

2023-03-31 20:30 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/Stats/StatsController.cs
> +            return;
Why return?

2023-03-31 20:30 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/Stats/StatsController.cs
> +
no space

2023-03-31 20:31 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/Stats/StatsController.cs
> +    private void Awake()
doesn't need to specify private since its default for void Awake()

2023-03-31 20:32 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/StatisticsController.cs
> +        }
Enums should be at the top in the class if they're private

2023-03-31 20:33 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/StatisticsController.cs
> +            // Set the default tab
Add space between line above comment

2023-03-31 20:33 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/StatisticsController.cs
> +
Remove spaces

2023-03-31 20:33 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/StatisticsController.cs
> +        }
Spacing between functions

2023-03-31 20:34 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/Settings/SettingsController.cs
> +
remove space

2023-03-31 20:34 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/Settings/SettingsController.cs
> +    private void Awake()
Doesn't have to be private, same reason as I wrote in the other comment

2023-03-31 20:35 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/Settings/SettingsController.cs
> +    }
Same with these two as other comment in statscontroller

2023-03-31 20:35 UTC, belgien commented on TrafficSimulator/Assets/UI/Statistics/Info/InfoController.cs
> +
remove space

2023-04-02 10:44 UTC, marc7s approved these changes

2023-04-02 22:37 UTC, merged