Double click bug fix
marc7s/TrafficSimulator pull request #120
Opened 2023-04-05 20:48 UTC by FelixJons

Made the select manager track its previous selected object. 

Also found fixed a bug with the coroutine in the default camera that was easily fixed once tracked down by simply stopping it upon changed object.

2023-04-05 22:59 UTC, marc7s requested changes

2023-04-05 22:59 UTC, marc7s commented on TrafficSimulator/Assets/Cam/ThirdPersonCamera.cs
> +            print("Rotate" + horizontalRotation);
```suggestion
```

2023-04-06 08:17 UTC, FelixJons commented on TrafficSimulator/Assets/Cam/ThirdPersonCamera.cs
> +            print("Rotate" + horizontalRotation);
Fixed!

2023-04-06 10:04 UTC, marc7s approved these changes

2023-04-06 10:04 UTC, merged