Set up graph for emission for world. Road color switch ui implemented, not connected yet.
marc7s/TrafficSimulator pull request #212
Opened 2023-05-14 13:21 UTC by FelixJons

2023-05-14 14:38 UTC, marc7s requested changes

2023-05-14 14:38 UTC, marc7s commented on TrafficSimulator/Assets/Old UI/GraphChartFeed.cs
> +        private void LoadGraph(TimeSpan timeSpan, int timeSpanInSeconds)
Just add the seconds to the TimeSpan enum, and int cast them here. Then you don't need the `timeSpanInSeconds`

```
private enum TimeSpan
        {
            None = 0,
            AllTime = -1,
            ThreeMinutes = 180,
            ThirtySeconds = 30
        }
```

Then just a check for if timespan is AllTime, then use the total elapsed time instead

2023-05-14 14:38 UTC, marc7s commented on TrafficSimulator/Assets/Plugins/Demigiant.meta
Do not bring these into the repo

Plugins should reside in the UnityAssets folder, untracked

2023-05-16 09:25 UTC, FelixJons commented on TrafficSimulator/Assets/Plugins/Demigiant.meta
Fixed!

2023-05-16 10:07 UTC, marc7s approved these changes

2023-05-16 10:07 UTC, merged