Dynamic brake snok & tuning AutoDrive
marc7s/TrafficSimulator pull request #30
Opened 2023-02-15 17:58 UTC by Marre-B

2023-02-15 18:18 UTC, hannes44 requested changes

2023-02-15 18:18 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +            print("Throttle" + _vehicleController.throttleInput);
Remove print

2023-02-15 18:18 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +            print(Vector3.Distance(transform.position, Q_GetBrakeTarget()));
Remove print

2023-02-15 18:18 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +            if (_brakeTarget.type = TargetType.Stop)
Maybe delete this commented code

2023-02-15 18:18 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +                _brakeDistance = 5 + (_vehicleController.speed / 2) + _vehicleController.speed * _vehicleController.speed / (_vehicleController.tireFriction * 9.81f);
Random addition with 5, should create constant for it in order to more easily understand why it is there

2023-02-15 18:18 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +            print("Brake distance: " + _brakeDistance);
Remove print

2023-02-15 18:18 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +            _targetLineRenderer.positionCount = 3;
could set the position count to the list length to make it easier to understand

2023-02-17 14:31 UTC, marc7s requested changes

2023-02-17 14:31 UTC, marc7s commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +        [Tooltip("How far from the stopping point the vehicle will come to a full stop at")]
```suggestion
        [Tooltip("How far from the stopping point the vehicle will come to a full stop")]
```

2023-02-17 14:31 UTC, marc7s commented on TrafficSimulator/Assets/Car/AutoDrive.cs
>          [SerializeField]
SerializeFields on same line

2023-02-17 14:31 UTC, marc7s commented on TrafficSimulator/Assets/Car/AutoDrive.cs
>          [Range(0, 20f)]
Range on same line as well

2023-02-17 14:31 UTC, marc7s commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +            _targetLookaheadDistance = _baseTLD * Math.Max(_vehicleController.speed / 20, 1);
Magic numbers, place in descriptive constants

2023-02-17 14:31 UTC, marc7s commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +                if (_targetIndex >= _lane.Count -1)
```suggestion
                if (_targetIndex + 1 >= _lane.Count)
```

2023-02-17 14:31 UTC, marc7s commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +                if (_targetIndex >= _lane.Count -1)
Makes the logic clearer

2023-02-17 14:31 UTC, marc7s commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +            /*
Remove commented code.
If you need it later you can find it in the commit history

2023-02-17 14:31 UTC, marc7s commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +                _repositioningTargetIndex = (_targetIndex - _repositioningOffset + _lane.Count) % _lane.Count;
This logic should be moved outside, for example to a `getNextIndex(int index)` function since this logic is duplicated a lot

2023-02-17 14:31 UTC, marc7s commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +        // Draw snoks for target and brake target
```suggestion
        // Draw lines towards steering and braking target
```

2023-02-17 14:31 UTC, marc7s commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +            if (_showTargetLines == ShowTargetLines.Target)
This would be nicer as a switch statement

2023-02-17 16:02 UTC, marc7s approved these changes

2023-02-17 16:03 UTC, hannes44 approved these changes

2023-02-17 16:03 UTC, merged