Car spawner
marc7s/TrafficSimulator pull request #45
Opened 2023-02-26 14:15 UTC by belgien

Finished a first version of car spawner

2023-02-26 14:45 UTC, marc7s requested changes

2023-02-26 14:45 UTC, marc7s commented on TrafficSimulator/Assets/CarSpawner.cs
> +                _offset = _lanes[i].StartNode.Count / carsToSpawn;
Possible division by 0

2023-02-26 14:45 UTC, marc7s commented on TrafficSimulator/Assets/CarSpawner.cs
> +                int carsToSpawn = (int)Mathf.Ceil(_ratios[i] * maxCars);
```suggestion
                int carsToSpawn = Mathf.CeilToInt(_ratios[i] * maxCars);
```
Try this instead so you don't have to cast

2023-02-26 14:45 UTC, marc7s commented on TrafficSimulator/Assets/CarSpawner.cs
> +                _offset = _lanes[i].StartNode.Count / carsToSpawn;
Possible division by 0 again

2023-02-26 14:45 UTC, marc7s commented on TrafficSimulator/Assets/CarSpawner.cs
> +                    // Check if max cars have been _spawned
```suggestion
                    // Check if max cars have been spawned
```

2023-02-26 14:45 UTC, marc7s commented on TrafficSimulator/Assets/RoadGenerator/Core/Runtime/Objects/LaneNode.cs
> +        public Vehicle _vehicle;
This should definately not be public

2023-02-26 14:45 UTC, marc7s commented on TrafficSimulator/Assets/RoadGenerator/Core/Runtime/Objects/Lane.cs
> +        public Road _road;
This does not need to be public

2023-02-26 14:45 UTC, marc7s commented on TrafficSimulator/Assets/Freecam.cs
> +    private float x;
Variable naming on all of these

2023-02-26 14:45 UTC, marc7s commented on TrafficSimulator/Assets/CarSpawner.cs
> +        private void Set_Offset(int _offset)
Function naming

2023-02-26 14:45 UTC, marc7s commented on TrafficSimulator/Assets/CarSpawner.cs
> +        [SerializeField] protected bool Mode = false; // True = Spawn cars with ratio, False = Spawn cars with percentage
This should be a SpawnMode enum instead

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +        [SerializeField] public Road _road;
Incorrect coding standard and shouldnät use serializeField for public

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +        [SerializeField] public int _laneIndex = 0;
Same here

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +        public LaneNode _currentNode;
Coding standard

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +        public void Start()
Create a setup function to avoid having a public start function

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +                //Q_TeleportToLane();
Should not be commented

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/Car/AutoDrive.cs
> +                //P_MoveToFirstPosition();
Should not be commented

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/CarSpawner.cs
> +        [SerializeField] private GameObject carPrefab;
Coding standard

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/CarSpawner.cs
> +        [SerializeField] private GameObject roadSystem;
Coding standard

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/CarSpawner.cs
> +        [SerializeField] private GameObject roadSystem;
Should change the name to roadSystemObject as there is another variable called _roadSystem

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/CarSpawner.cs
> +        public float Distance = 10f; // Distance between cars
Unused variable

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/CarSpawner.cs
> +        private int _maxCars;
Unused variable

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/CarSpawner.cs
> +        private LaneNode _laneNodeTemp;
Unused variable

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/CarSpawner.cs
> +                _offset = _lanes[i].StartNode.Count / carsToSpawn;
Could get divide by zero

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/CarSpawner.cs
> +                Debug.Log("Cars to spawn: " + carsToSpawn + " on lane " + i + " with " + _maxCarsPerLane[i] + " max cars");
Should remove log

2023-02-26 14:45 UTC, hannes44 commented on TrafficSimulator/Assets/CarSpawner.cs
> +        private void Set_Offset(int _offset)
Coding Standard, remove underscore

2023-02-26 17:19 UTC, marc7s requested changes

2023-02-26 17:19 UTC, marc7s commented on TrafficSimulator/Assets/Car/CarSpawner.cs
> +                if (carsToSpawn == 0)
Add a comment that this is to avoid division by zero for transparency and maintainability

2023-02-26 17:19 UTC, marc7s commented on TrafficSimulator/Assets/Car/CarSpawner.cs
> +                    _carCounter = _carCounter + 1;
```suggestion
                    _carCounter++;
```

2023-02-26 17:19 UTC, marc7s commented on TrafficSimulator/Assets/Car/CarSpawner.cs
> +            int cars_Spawned = 0;
This should be named `carsSpawned`

2023-02-26 17:19 UTC, marc7s commented on TrafficSimulator/Assets/Car/CarSpawner.cs
> +                    cars_Spawned = cars_Spawned + 1;
```suggestion
                    cars_Spawned++;
```

2023-02-26 17:19 UTC, marc7s commented on TrafficSimulator/Assets/Car/CarSpawner.cs
> +                    _carCounter = _carCounter + 1;
```suggestion
                    _carCounter++;
```

2023-02-26 17:19 UTC, marc7s commented on TrafficSimulator/Assets/Car/CarSpawner.cs
> +            for (int i = 0; i < _lanes.Count; i++)
The spawn code should be made into its own function as it is used multiple times. As it stands there is code duplication

2023-02-27 17:19 UTC, marc7s requested changes

2023-02-27 17:19 UTC, marc7s commented on TrafficSimulator/Assets/Car/CarSpawner.cs
> +                _maxCarsPerLane.Add((int)(_lengths[j] / CarLength));
Nicer with a `floor` instead of an int cast

2023-02-27 17:19 UTC, marc7s commented on TrafficSimulator/Assets/Car/CarSpawner.cs
> +                {
Formatting

2023-02-27 17:19 UTC, marc7s commented on TrafficSimulator/Assets/Car/CarSpawner.cs
> +            _currentCar.GetComponent<AutoDrive>().CustomStartNode = _laneNodeCurrent.Next.Next;
Bug for short roads

2023-02-27 17:19 UTC, marc7s commented on TrafficSimulator/Assets/RoadGenerator/Core/Runtime/Objects/Lane.cs
> +        public float GetLaneLength()
Should be private

2023-02-27 17:19 UTC, marc7s commented on TrafficSimulator/Assets/RoadGenerator/Core/Runtime/Objects/Lane.cs
> +                length += Vector3.Distance(curr.Position, curr.Next.Position);
Use `DistanceToPrevNode` instead

2023-02-27 17:19 UTC, marc7s commented on TrafficSimulator/Assets/RoadGenerator/Core/Runtime/Objects/Lane.cs
> +            while(curr.Next != null)
Misses the last node so distance will be incorrect

2023-02-27 17:36 UTC, marc7s approved these changes

2023-02-27 17:37 UTC, merged